on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dnazureacr1234.azurecr.io
        username: ${{ secrets.acr_dnazureacr1234_username }}
        password: ${{ secrets.acr_dnazureacr1234_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/OrderItem" -f  "OrderItem/Dockerfile" -t dnazureacr1234.azurecr.io/dnazureaks12:${{ github.sha }} --label dockerfile-path=OrderItem/Dockerfile
        docker push dnazureacr1234.azurecr.io/dnazureaks12:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dnazureaks12_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dnazure-aks12baf3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dnazure-aks12baf3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dnazure-aks12baf3
        container-registry-url: dnazureacr1234.azurecr.io
        container-registry-username: ${{ secrets.acr_dnazureacr1234_username }}
        container-registry-password: ${{ secrets.acr_dnazureacr1234_password }}
        secret-name: dnazureaks12dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dnazure-aks12baf3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dnazureacr1234.azurecr.io/dnazureaks12:${{ github.sha }}
        imagepullsecrets: |
          dnazureaks12dockerauth
